#!/bin/bash
#
#	/etc/rc.d/init.d/blynk
#
# Starts blynk
#
# chkconfig: 345 95 5
# description: starts
# processname: blynk


PID=0
RETVAL=0
PROG="blynk" 
OPTS="-Xmx512m"

DIR="/home/dev/$PROG"
USER="dev"

VERSION="-1.0-SNAPSHOT.jar"

start() { 
    /opt/jdk/bin/java $OPTS -cp $DIR/$PROG$VERSION:$DIR/dependency/* com.balanko.TestFrame # > /var/log/$PROG/out 2> /var/log/$PROG/err &
    return $RETVAL
}

stop() {
    pgrep -u $USER -f $PROG-ws | xargs kill -9
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    restart
}

update() {
    STAGING_DIR=/tmp/$PROG
    /bin/rm -rf "$STAGING_DIR" && mkdir -p "$STAGING_DIR/"
    git clone --branch master --depth 1 git@github.com:jad939933/$PROG.git $STAGING_DIR

    JAVA_HOME=/opt/jdk /usr/local/maven/bin/mvn -f $STAGING_DIR/pom.xml -DskipTests -Dmaven.javadoc.skip=true clean compile install dependency:copy-dependencies

    if [ -d "$STAGING_DIR/target/dependency" ]; then
        stop
	echo "moving rm -rf $DIR && mv $STAGING_DIR/target $DIR"
	/bin/rm -rf $DIR && /bin/mv $STAGING_DIR/target $DIR
        start
    fi
}



status_at() {
    status /usr/sbin/$PROG
}

case "$1" in
start)
      	start
	;;
stop)
     	stop
	;;
reload|restart)
        restart
        ;;
update)
        update
        ;;

condrestart)
	if [ -f /var/lock/subsys/$PROG ]; then
            restart
        fi
	;;
status)
       	status_at
        ;;
*)
  	echo $"Usage: $0 {start|stop|restart|condrestart|status|info}"
        exit 1
esac

exit $?
exit $RETVAL

