#!/bin/bash
#
#	/etc/rc.d/init.d/blynk
#
# Starts blynk
#
### BEGIN INIT INFO
# Provides:          blynk
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: blynk service...
### END INIT INFO

PID=0
RETVAL=0
PROG="blynk"
OPTS="-Xmx256m -Djava.library.path=/usr/lib/jni/"
USER="pi"

DIR="/home/$USER/$PROG"
USER="dev"

VERSION="-1.0-SNAPSHOT.jar"

start() {
    #require: sudo apt-get install libjinput-java libjinput-jni
    sudo java $OPTS -cp /usr/share/java/*:$DIR/target/$PROG$VERSION:$DIR/target/dependency/* com.balanko.TestFrame --port=/dev/ttyS0 > /var/log/$PROG/out 2> /var/log/$PROG/err &
    return $RETVAL
}

stop() {
    sudo killall -9 java
    return $RETVAL
}

restart() {
    stop
    start
}

reload() {
    restart
}

update() {
    #git clone --branch master --depth 1 https://github.com/jad939933/$PROG.git $STAGING_DIR
    /usr/local/maven/bin/mvn -f $DIR/pom.xml -DskipTests -Dmaven.javadoc.skip=true clean compile install dependency:copy-dependencies
}



status_at() {
    status /usr/sbin/$PROG
}

case "$1" in
start)
      	start
	;;
stop)
     	stop
	;;
reload|restart)
        restart
        ;;
update)
        update
        ;;

condrestart)
	if [ -f /var/lock/subsys/$PROG ]; then
            restart
        fi
	;;
status)
       	status_at
        ;;
*)
  	echo $"Usage: $0 {start|stop|restart|condrestart|status|info}"
        exit 1
esac

exit $?
exit $RETVAL
